#!/bin/bash -e

# names the image as below
image="rcpch-dgc-demo-client"
container_name="rcpch-dgc-demo-client"

docker rm ${image} || true

# Build the Docker image
docker build -t ${image} .

# Run the Docker container with port mapping and container name
docker run -p 3000:3000 --name ${container_name} ${image}