# Runs the PR check script

name: Run PR checks

permissions:
  id-token: write
  contents: read

on:
  pull_request:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout full code repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          fetch-depth: 0 # to allow git_context_processor.py to still work

      - name: Install NPM packages
        run: npm ci

      - name: Build project
        env:
          BASE_PATH: /${{ github.event.repository.name }}/
          VITE_APP_GROWTH_API_BASEURL: ${{ secrets.VITE_APP_GROWTH_API_BASEURL }}
          VITE_APP_API_KEY: ${{secrets.VITE_APP_API_KEY }}
        run: npm run build